<h2>Decode</h2>
<code>POST&nbsp;https://nenscript.herokuapp.com/api/v1.0/decode</code>
<h3>Request</h3>
<table class="table table-bordered">
    <tr>
        <th width="25%">Name</th>
        <th width="50%">Description</th>
        <th width="25%">Type</th>
    </tr>
    <tr>
        <td>text</td>
        <td>Text to decode</td>
        <td>string</td>
    </tr>
</table>
<h3>Response</h3>
<table class="table table-bordered">
    <tr>
        <th width="25%">Name</th>
        <th width="50%">Description</th>
        <th width="25%">Type</th>
    </tr>
    <tr>
        <td>decoded</td>
        <td>Decoded text</td>
        <td>string</td>
    </tr>
</table>
<h2>Encode</h2>
<code>POST&nbsp;https://nenscript.herokuapp.com/api/v1.0/encode</code>
<h3>Request</h3>
<table class="table table-bordered">
    <tr>
        <th width="25%">Name</th>
        <th width="50%">Description</th>
        <th width="25%">Type</th>
    </tr>
    <tr>
        <td>text</td>
        <td>Text to encode</td>
        <td>string</td>
    </tr>
</table>
<h3>Response</h3>
<table class="table table-bordered">
    <tr>
        <th width="25%">Name</th>
        <th width="50%">Description</th>
        <th width="25%">Type</th>
    </tr>
    <tr>
        <td>encoded</td>
        <td>Encoded text</td>
        <td>string</td>
    </tr>
</table>