<form method="get">
    <div class="form-group">
        <label for="text">English:</label>
        <textarea id="text" name="text" class="form-control"><?= $text ?? '' ?></textarea>
    </div>
    <div class="form-group">
        <label for="result">Nen:</label>
        <textarea disabled id="result" name="result" class="form-control"><?= $result ?? '' ?></textarea>
    </div>
    <button class="btn btn-default" type="submit">Decode</button>
    <a class="btn btn-default" href="/decode.html" role="button">Restart</a>
</form>