<form method="post">
    <div class="form-group">
        <label for="content">English:</label>
        <textarea id="content" name="content" class="form-control"><?= $content ?? '' ?></textarea>
    </div>
    <div class="form-group">
        <label for="result">Nen:</label>
        <textarea disabled id="result" name="result" class="form-control"><?= $result ?? '' ?></textarea>
    </div>
    <button class="btn btn-default" type="submit">Decode</button>
    <a class="btn btn-default" href="/decode.html" role="button">Restart</a>
</form>