<form method="post">
    <label for="content">Nen:</label>
    <textarea style="width: 100%; height: 100px" id="content" name="content"><?= isset($content) ? $content : null; ?></textarea>
    <label for="result">English:</label>
    <textarea disabled style="width: 100%; height: 100px" id="result" name="result"><?= isset($result) ? $result : null; ?></textarea>
    <button type="submit">Submit</button>
    <br>
    <a href="/encode.html">Restart</a>
    <br>
    <a href="/decode.html">English => Nen</a>
</form>