<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title><?= $title ?? '' ?></title>

    <link href="/css/bootstrap.min.css" rel="stylesheet">
    <link href="/css/styles.css" rel="stylesheet">

    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <div class="container">
        <div class="header clearfix">
            <h1>NEN script</h1>
            <nav>
                <ul class="nav nav-pills">
                    <li<?php if (isset($menu) && $menu === 'home'): ?> class="active"<?php endif; ?>>
                        <a href="/">Home</a>
                    </li>
                    <li<?php if (isset($menu) && $menu === 'decode'): ?> class="active"<?php endif; ?>>
                        <a href="/decode.html">Decode</a>
                    </li>
                    <li<?php if (isset($menu) && $menu === 'encode'): ?> class="active"<?php endif; ?>>
                        <a href="/encode.html">Encode</a>
                    </li>
                    <li<?php if (isset($menu) && $menu === 'api'): ?> class="active"<?php endif; ?>>
                        <a href="/api.html">API</a>
                    </li>
                </ul>
            </nav>
        </div>

        <div class="row">
            <div class="col-md-12">
                <?= $this->getContent(); ?>
            </div>
        </div>

        <footer class="footer">
            <p>&copy; <?= date('Y'); ?> <a href="https://nenscript.herokuapp.com/">NEN script</a>.</p>
        </footer>
    </div>

    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
        ga('create', 'UA-92264214-1', 'auto');
        ga('send', 'pageview');
    </script>
</body>
